<section>
  <h1><?php echo $this->translate('Bulk bookings'); ?></h1>

  <nav>
    <ul>
      <li>
        <a href="<?php echo $this->url(array('action' => 'template')); ?>"
           title="<?php echo $this->translate('Download a template to assist you with preparing bulk bookings'); ?>"
           ui-jq="tooltip"><?php echo $this->translate('Download template'); ?></a>
      </li>
    </ul>
  </nav>
  <?php echo $this->form; ?>
</section>
