<section>
  <h1><?php echo $this->translate('Facilities'); ?></h1>

  <nav>
    <ul>
      <li>
        <a href="<?php echo $this->url(array('module' => 'facility', 'controller' => 'facility', 'action' => 'create1'), null, true); ?>"
        ><?php echo $this->translate('Create facility'); ?></a>
      </li>
      <!--<li>
        <a title="<?php echo $this->translate('Find available facilities'); ?>"
           href="<?php echo $this->url(array('controller' => 'search', 'action' => 'index')); ?>"><?php echo $this->translate('Find available facilities'); ?></a>
      </li>-->
    </ul>
  </nav>
</section>

<div class="yui3-g">
  <div class="yui3-u-1-2">
    <section>
      <h2><?php echo $this->translate('Find facility group'); ?></h2>

      <?php echo $this->facilityGroupForm; ?>
    </section>
  </div>

  <div class="yui3-u-1-2">
    <section>
      <h2><?php echo $this->translate('Find facility'); ?></h2>

      <?php echo $this->facilityForm; ?>
    </section>
  </div>
</div>

<script type="text/javascript">
$(function() {
  $('#facilitygroup-name')
  .bind('autocompleteselect', function(e, ui) {
    e.preventDefault();

    window.location = ui.item.uri;
  })
  .autocomplete({
    source: function(req, resp) {
      var term = req.term;

      $.getJSON(
        '<?php echo $this->url(array('controller' => 'facilitygroup', 'action' => 'autocomplete')); ?>?q=' + term,
        resp
      );
    }
  });

  $('#facility-name')
  .bind('autocompleteselect', function(e, ui) {
    e.preventDefault();

    window.location = ui.item.uri;
  })
  .autocomplete({
    source: function(req, resp) {
      var term = req.term;

      $.getJSON(
        '<?php echo $this->url(array('controller' => 'facility', 'action' => 'autocomplete')); ?>?q=' + term,
        resp
      );
    }
  });
});
</script>
