<section>
  <h1><?php printf($this->translate(
    'Facility group %1$s',
    $this->escape($this->facilityGroup->configs->last()->name)
  )); ?></h1>

  <nav>
    <ul>
      <li>
        <a title="<?php echo $this->translate('Create a new facility group configuration'); ?>"
           href="<?php echo $this->url(array('module' => 'facility', 'controller' => 'facilitygroupconfig', 'action' => 'create', 'facilitygroup_id' => $this->facilityGroup->id), null, true); ?>"
        ><?php echo $this->translate('Create configuration'); ?></a>
      </li>
    </ul>
  </nav>

  <?php echo $this->dataTableFacilityGroupConfiguration($this->configRows); ?>
</section>
