<section>
  <h1><?php echo sprintf($this->translate('%s status'), $this->escape($this->job->getName())) ?></h1>

  <p><?php echo $this->escape($this->job->getDescription()) ?></p>

<?php if ($this->jobEntity->is_dry_run): ?>
  <p>
    <strong><?php echo $this->translate('This job was created as a dry run, meaning no permanent changes were made.') ?></strong>
  </p>
<?php endif ?>
  <div class="yui3-g">
    <div class="yui3-u-1-2">
      <h2><?php echo $this->translate('Job information') ?></h2>
      <dl>
        <dt><?php echo $this->translate('Job name') ?></dt>
        <dd><?php echo $this->escape($this->job->getName()) ?></dd>
        <dt><?php echo $this->translate('Started at') ?></dt>
        <dd><?php echo $this->markupDateTime($this->jobEntity->created_at) ?></dd>
        <dt><?php echo $this->translate('Updated at') ?></dt>
        <dd><?php echo $this->markupDateTime($this->jobEntity->updated_at) ?></dd>
      </dl>
    </div>
    <div class="yui3-u-1-2">
      <h2><?php echo $this->translate('Job parameters') ?></h2>
      <dl>
<?php foreach ($this->jobEntity->parameters as $parameter): ?>
        <dt><?php echo $this->escape($parameter->label) ?></dt>
        <dd><?php echo $this->escape($parameter->value) ?></dd>
<?php endforeach ?>
      </dl>
    </div>
  </div>

  <h2>Files</h2>
<?php if (count($this->jobEntity->attachments) === 0): ?>
  <p><?php echo $this->translate('This job has not created any attachments.') ?></p>
<?php else: ?>
  <ul>
    <?php foreach ($this->jobEntity->attachments as $attachment): ?>
    <li><a href="<?php echo $this->url(array('controller' => 'attachment', 'action' => 'view', 'id' => $attachment->id)) ?>"><?php echo $this->escape($attachment->name) ?></a></li>
    <?php endforeach ?>
  </ul>
<?php endif ?>

  <h2>Messages</h2>
<?php if (count($this->jobEntity->messages) === 0): ?>
  <p><?php echo $this->translate('This job has not created any messages.') ?></p>
<?php else: ?>
  <ul>
    <?php foreach ($this->jobEntity->messages as $message): ?>
    <li><?php echo $this->escape($message->message) ?></li>
    <?php endforeach ?>
  </ul>
<?php endif ?>
</section>

<script type="text/javascript">
<?php if ($this->jobEntity->run_state !== \Tillikum\Entity\Job\Job::RUN_STATE_STOPPED): ?>
window.setTimeout(function() {
  window.location.reload(1);
}, 5000);
<?php endif ?>
</script>
