<?php
$personUri = $this->url(
    array(
        'module' => 'person',
        'controller' => 'person',
        'action' => 'view',
        'id' => $this->person->id
    ),
    null,
    true
);

$personLink = sprintf(
    '<a href="%s">%s</a>',
    $personUri,
    $this->escape($this->person->display_name)
);
?>

<section>
  <h1><?php echo $this->translate('Edit meal plan booking for %1$s', $personLink); ?></h1>

  <?php if ($this->clearSessionUri): ?>
  <div role="alert" data-is-info="true"><?php echo sprintf($this->translate('You are seeing unsaved changes here, and they may not reflect what is currently in the database. You may <a href="%s">clear</a> them to start over.', $this->clearSessionUri)) ?></div>
  <?php endif ?>

  <?php echo $this->form; ?>
</section>
