<table id="pending-booking-summary">
  <caption><?php echo $this->translate('Pending booking lists') ?></caption>
  <thead>
    <tr>
      <th><?php echo $this->translate('Name') ?></th>
      <th><?php echo $this->translate('Description') ?></th>
      <th><?php echo $this->translate('Actions') ?></th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($this->rows as $row): ?>
    <tr>
      <td><?php echo $this->escape($row['name']) ?></td>
      <td><?php echo $this->escape($row['description']) ?></td>
      <td class="nowrap">
        <ul class="ui-widget">
    <?php if ($row['actions']['view']): ?>
          <li class="ui-state-default ui-corner-all">
            <a href="<?php echo $row['view_uri'] ?>"><span class="ui-icon ui-icon-zoomin" title="<?php echo $this->translate('View details…') ?>" ui-jq="tooltip"></span></a>
          </li>
    <?php endif ?>
        </ul>
      </td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>

<script type="text/javascript">
$(function() {
  $('#pending-booking-summary').dataTable({
    aaSorting: [[0, 'asc']]
  });
});
</script>
