<table id="booking-mealplan-confirm">
  <caption><?php echo $this->translate('Meal plan booking confirmation') ?></caption>
  <thead>
    <tr>
      <th><?php echo $this->translate('Meal plan') ?></th>
      <th><?php echo $this->translate('Start date') ?></th>
      <th><?php echo $this->translate('End date') ?></th>
      <th><?php echo $this->translate('Notes') ?></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->rows as $row): ?>
    <tr>
      <td><?php echo $this->escape($row['name']) ?></td>
      <td><?php echo $this->markupDate($row['start']) ?></td>
      <td><?php echo $this->markupDate($row['end']) ?></td>
      <td><?php echo nl2br($this->escape($row['note'])) ?></td>
    </tr>
<?php endforeach ?>
  </tbody>
</table>

<script type="text/javascript">
$(function() {
  $('#booking-mealplan-confirm').dataTable({
    aaSorting: [[1, 'desc']],
    aoColumnDefs: [
      { sType: 'time-html', aTargets: [1, 2] }
    ]
  });
});
</script>
