<table id="booking-mealplan-billing-rate-confirm">
  <caption><?php echo $this->translate('Billing rate confirmation'); ?></caption>
  <thead>
    <tr>
      <th><?php echo $this->translate('Rule'); ?></th>
      <th><?php echo $this->translate('Start date'); ?></th>
      <th><?php echo $this->translate('End date'); ?></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->rows as $row): ?>
    <tr>
      <td><?php echo $this->escape($row['rule_description']); ?></td>
      <td><?php echo $this->markupDate($row['start']); ?></td>
      <td><?php echo $this->markupDate($row['end']); ?></td>
    </tr>
<?php endforeach; ?>
  </tbody>
</table>

<script type="text/javascript">
$(function() {
  $('#booking-mealplan-billing-rate-confirm').dataTable({
    aaSorting: [[0, 'desc']],
    aoColumnDefs: [
      { sType: 'time-html', aTargets: [1, 2] }
    ]
  });
});
</script>
