<section>
  <h1><?php echo $this->translate('Reporting'); ?></h1>

  <table id="report-summary">
    <caption><?php echo $this->translate('Report listing'); ?></caption>
    <thead>
      <tr>
        <th><?php echo $this->translate('Name'); ?></th>
        <th><?php echo $this->translate('Description'); ?></th>
        <th><?php echo $this->translate('Actions'); ?></th>
      </tr>
    </thead>
    <tbody>
<?php foreach ($this->reportSummary as $row): ?>
      <tr>
        <td><?php echo $this->escape($row['name']); ?></td>
        <td><?php echo $this->escape($row['description']); ?></td>
        <td class="nowrap">
          <ul class="ui-widget">
            <li class="ui-state-default ui-corner-all">
              <a href="<?php echo $this->url(array('action' => 'view', 'controller' => 'report', 'name' => $row['serviceName'])); ?>"><span class="ui-icon ui-icon-zoomin" title="<?php echo $this->translate('View…'); ?>" ui-jq="tooltip"></span></a>
            </li>
          </ul>
        </td>
      </tr>
<?php endforeach; ?>
    </tbody>
  </table>
</section>

<script type="text/javascript">
$(function() {
  $('#report-summary').dataTable({
    iDisplayLength: 25
  });
});
</script>
