<section>
  <h1><?php echo $this->translate('Billing rules') ?></h1>
  <nav>
    <ul>
      <li><a href="<?php echo $this->url(array('controller' => 'rule', 'action' => 'create1')); ?>" title="<?php echo $this->translate('Create a new billing rule'); ?>" ui-jq="tooltip"><?php echo $this->translate('Create rule'); ?></a></li>
    </ul>
  </nav>
  <?php echo $this->dataTableBillingRuleAdHoc($this->adHocRuleData) ?>
  <?php echo $this->dataTableBillingRuleFacilityBooking($this->facilityBookingRuleData) ?>
  <?php echo $this->dataTableBillingRuleMealplanBooking($this->mealplanBookingRuleData) ?>
</section>
