<section>
  <h1><?php echo $this->translate('Billing rules') ?></h1>
  <nav>
    <ul>
      <li><a href="<?php echo $this->url(array('controller' => 'rule', 'action' => 'create1')); ?>" title="<?php echo $this->translate('Create a new billing rule'); ?>" ui-jq="tooltip"><?php echo $this->translate('Create rule'); ?></a></li>
    </ul>
  </nav>
  <div id="billing-rules-tabs" ui-jq="tabs">
    <ul>
      <li><a href="#rule-adhoc"><?php echo $this->translate('Ad hoc billing') ?></a></li>
      <li><a href="#rule-facility"><?php echo $this->translate('Facility booking billing') ?></a></li>
      <li><a href="#rule-mealplan"><?php echo $this->translate('Meal plan booking billing') ?></a></li>
    </ul>
    <section id="rule-adhoc">
      <?php echo $this->dataTableBillingRuleAdHoc($this->adHocRuleData) ?>
    </section>
    <section id="rule-facility">
      <?php echo $this->dataTableBillingRuleFacilityBooking($this->facilityBookingRuleData) ?>
    </section>
    <section id="rule-mealplan">
      <?php echo $this->dataTableBillingRuleMealplanBooking($this->mealplanBookingRuleData) ?>
    </section>
  </div>
</section>
