<table id="billing-event-adhoc">
  <caption><?php echo $this->translate('Ad hoc billing events') ?></caption>
  <thead>
    <th><?php echo $this->translate('Rule') ?></th>
    <th><?php echo $this->translate('Person') ?></th>
    <th><?php echo $this->translate('Amount') ?></th>
    <th><?php echo $this->translate('Description') ?></th>
    <th><?php echo $this->translate('Effective') ?></th>
    <th><?php echo $this->translate('Processed?') ?></th>
    <th><?php echo $this->translate('Created at') ?></th>
  </thead>
  <tbody>
  <?php foreach ($this->rows as $row): ?>
    <tr data-id="<?php echo $this->escape($row['id']) ?>">
      <td><?php echo $this->escape($row['rule']) ?></td>
      <td><?php echo $row['person_html'] ?></td>
      <td><?php echo $this->markupCurrency($row['amount'], $row['currency']); ?></td>
      <td><?php echo $this->escape($row['description']) ?></td>
      <td><?php echo $this->markupDate($row['effective']) ?></td>
      <td><?php echo $row['is_processed'] ? $this->translate('Yes') : $this->translate('No') ?></td>
      <td><span title="<?php echo $this->translate('Created by %s', $this->escape($row['created_by'])) ?>"><?php echo $this->markupDateTime($row['created_at']) ?></span></td>
    </tr>
  <?php endforeach ?>
  </tbody>
</table>

<script type="text/javascript">
$(function() {
  $('#billing-event-adhoc').dataTable({
    aaSorting: [[6, 'desc']],
    aoColumnDefs: [
      { sType: 'time-html', aTargets: [4, 6] }
    ],
    iDisplayLength: 10
  });
  $('#billing-event-adhoc [title]').tooltip();
});
</script>
