<table id="billing-rule-facility-booking-config">
  <caption><?php echo $this->translate('Facility booking billing rule configuration') ?></caption>
  <thead>
    <th><?php echo $this->translate('Rule description') ?></th>
    <th><?php echo $this->translate('Configuration description') ?></th>
    <th><?php echo $this->translate('Code') ?></th>
    <th><?php echo $this->translate('Strategy') ?></th>
    <th><?php echo $this->translate('Amount') ?></th>
    <th><?php echo $this->translate('Start date') ?></th>
    <th><?php echo $this->translate('End date') ?></th>
    <th><?php echo $this->translate('Created at') ?></th>
    <th><?php echo $this->translate('Updated at') ?></th>
    <th><?php echo $this->translate('Actions') ?></th>
  </thead>
  <tbody>
  <?php foreach ($this->rows as $row): ?>
    <tr data-id="<?php echo $this->escape($row['id']) ?>">
      <td><?php echo $this->escape($row['rule']->description) ?></td>
      <td><?php echo $this->escape($row['description']) ?></td>
      <td><?php echo $this->escape($row['code']) ?></td>
      <td><span title="<?php echo $this->escape($row['strategy_description']) ?>" ui-jq="tooltip"><?php echo $this->escape($row['strategy_name']) ?></span></td>
      <td><?php echo $this->markupCurrency($row['amount'], $row['currency']) ?></td>
      <td><?php echo $this->markupDate($row['start']) ?></td>
      <td><?php echo $this->markupDate($row['end']) ?></td>
      <td><span title="<?php echo $this->translate('Created by %s', $this->escape($row['created_by'])) ?>" ui-jq="tooltip"><?php echo $this->markupDateTime($row['created_at']) ?></span></td>
      <td><span title="<?php echo $this->translate('Updated by %s', $this->escape($row['updated_by'])) ?>" ui-jq="tooltip"><?php echo $this->markupDateTime($row['updated_at']) ?></span></td>
      <td class="nowrap">
        <ul class="ui-widget">
    <?php if ($row['actions']['edit']): ?>
          <li class="ui-state-default ui-corner-all">
            <a href="<?php echo $row['edit_uri'] ?>"><span class="ui-icon ui-icon-pencil" title="<?php echo $this->translate('Edit…') ?>" ui-jq="tooltip"></span></a>
          </li>
    <?php endif ?>
    <?php if ($row['actions']['copy']): ?>
          <li class="ui-state-default ui-corner-all">
            <a href="<?php echo $row['copy_uri'] ?>"><span class="ui-icon ui-icon-copy" title="<?php echo $this->translate('Copy…') ?>" ui-jq="tooltip"></span></a>
          </li>
    <?php endif ?>
    <?php if ($row['actions']['delete']): ?>
          <li class="ui-state-default ui-corner-all">
            <a href="<?php echo $row['delete_uri'] ?>"><span class="ui-icon ui-icon-trash" title="<?php echo $this->translate('Delete…') ?>" ui-jq="tooltip"></span></a>
          </li>
    <?php endif ?>
        </ul>
      </td>
    </tr>
  <?php endforeach ?>
  </tbody>
</table>

<script type="text/javascript">
$(function() {
  $('#billing-rule-facility-booking-config').dataTable({
    aaSorting: [[5, 'desc']],
    aoColumnDefs: [
      { sType: 'data-money', aTargets: [4] },
      { sType: 'time-html', aTargets: [5, 6, 7, 8] }
    ],
    iDisplayLength: 25,
    sDom: '<"H"f>t<"F"ip>'
  });
});
</script>
