<section>
  <h1><?php echo $this->translate('Billing'); ?></h1>
  <nav>
    <ul>
      <li><a href="<?php echo $this->url(array('controller' => 'rule', 'action' => 'create1')); ?>" title="<?php echo $this->translate('Create a new billing rule'); ?>"><?php echo $this->translate('Create rule'); ?></a></li>
      <li><a href="<?php echo $this->url(array('controller' => 'rule', 'action' => 'index')); ?>" title="<?php echo $this->translate('View billing rules'); ?>"><?php echo $this->translate('View rules'); ?></a></li>
      <!--<li><a href="<?php echo $this->url(array('controller' => 'bulk', 'action' => 'index')); ?>" title="<?php echo $this->translate('Perform billing in bulk'); ?>"><?php echo $this->translate('Bulk billing'); ?></a></li>-->
    </ul>
  </nav>
</section>
