<table id="facility-search">
  <caption><?php echo $this->translate('Facility search results') ?></caption>
  <thead>
    <th><?php echo $this->translate('Start date') ?></th>
    <th><?php echo $this->translate('End date') ?></th>
    <th><?php echo $this->translate('Facility group') ?></th>
    <th><?php echo $this->translate('Facility') ?></th>
    <th><?php echo $this->translate('Gender') ?></th>
    <th><?php echo $this->translate('Capacity') ?></th>
    <th><?php echo $this->translate('Notes') ?></th>
    <th><?php echo $this->translate('Tags') ?></th>
    <th><?php echo $this->translate('Available spaces') ?></th>
    <th><?php echo $this->translate('Actions') ?></th>
  </thead>
  <tbody>
<?php foreach ($this->rows as $row): ?>
    <tr data-id="<?php echo $this->escape($row['id']) ?>">
      <td><?php echo $this->markupDate($row['start']) ?></td>
      <td><?php echo $this->markupDate($row['end']) ?></td>
      <td><?php echo $this->escape($row['facility_group']) ?></td>
      <td><?php echo $this->escape($row['facility']) ?></td>
      <td><?php echo $this->escape($row['gender']) ?></td>
      <td><?php echo $this->escape($row['capacity']) ?></td>
      <td><?php echo nl2br($this->escape($row['note'])) ?></td>
      <td>
  <?php if (count($row['tags']) > 0): ?>
        <ul class="separated"><!--
    <?php foreach ($row['tags'] as $tag): ?>
          --><li><?php echo $this->escape($tag->name) ?></li><!--
    <?php endforeach ?>
        --></ul>
  <?php endif ?>
      </td>
      <td><?php echo $this->escape($row['availableSpace']) ?></td>
      <td class="nowrap">
        <ul class="ui-widget">
  <?php if ($row['actions']['view']): ?>
          <li class="ui-state-default ui-corner-all">
            <a href="<?php echo $row['view_uri']; ?>"><span class="ui-icon ui-icon-zoomin" title="<?php echo $this->translate('View…'); ?>" ui-jq="tooltip"></span></a>
          </li>
  <?php endif; ?>
        </ul>
      </td>
    </tr>
<?php endforeach ?>
  </tbody>
</table>

<script type="text/javascript">
$(function() {
  $('#facility-search').dataTable({
    aaSorting: [[0, 'desc']],
    aoColumnDefs: [
      { sType: 'time-html', aTargets: [0, 1] }
    ],
    sDom: '<"H">t<"F"ip>'
  });
});
</script>
