<table id="facility-booking">
  <caption><?php echo $this->translate('People booked to this facility'); ?></caption>
  <thead>
    <th><?php echo $this->translate('Person'); ?></th>
    <th><?php echo $this->translate('Gender'); ?></th>
    <th><?php echo $this->translate('Start date'); ?></th>
    <th><?php echo $this->translate('End date'); ?></th>
    <th><?php echo $this->translate('Actions'); ?></th>
  </thead>
  <tbody>
<?php foreach ($this->rows as $row): ?>
  <?php $attr = ''; ?>
  <?php if ($row['is_current']): ?>
    <?php $attr = 'title="' . $this->translate('This booking is current.') . '" data-is-info="true" ui-jq="tooltip"'; ?>
  <?php endif; ?>

    <tr data-id="<?php echo $this->escape($row['id']); ?>" <?php echo $attr; ?>>
      <td><a href="<?php echo $this->escape($row['person_uri']); ?>"><?php echo $this->escape($row['person_name']); ?></a></td>
      <td><?php echo $this->escape($row['person_gender']); ?></td>
      <td><?php echo $this->markupDate($row['start']); ?></td>
      <td><?php echo $this->markupDate($row['end']); ?></td>
      <td class="nowrap">
        <ul class="ui-widget">
  <?php if ($row['actions']['details']): ?>
          <li class="ui-state-default ui-corner-all">
            <a href="<?php echo $row['details_uri']; ?>"><span class="ui-icon ui-icon-zoomin" title="<?php echo $this->translate('View details…'); ?>" ui-jq="tooltip"></span></a>
          </li>
  <?php endif; ?>
  <?php if ($row['actions']['edit']): ?>
          <li class="ui-state-default ui-corner-all">
            <a href="<?php echo $row['edit_uri']; ?>"><span class="ui-icon ui-icon-pencil" title="<?php echo $this->translate('Edit…'); ?>" ui-jq="tooltip"></span></a>
          </li>
  <?php endif; ?>
  <?php if ($row['actions']['delete']): ?>
          <li class="ui-state-default ui-corner-all">
            <a href="<?php echo $row['delete_uri']; ?>"><span class="ui-icon ui-icon-trash" title="<?php echo $this->translate('Delete…'); ?>" ui-jq="tooltip"></span></a>
          </li>
  <?php endif; ?>
        </ul>
      </td>
    </tr>
<?php endforeach; ?>
  </tbody>
</table>

<script type="text/javascript">
$(function() {
  $('#facility-booking').dataTable({
    aaSorting: [[2, 'desc']],
    aoColumnDefs: [
      { sType: 'time-html', aTargets: [2, 3] }
    ],
    bJQueryUI: true,
    sDom: '<"H">t<"F"ip>'
  });
});
</script>
