<?php
$this->headMeta()->setCharset($this->getEncoding());
$this->headMeta()->setHttpEquiv('X-UA-Compatible', 'IE=edge env=best-standards-support');
$this->headMeta()->setName('viewport', 'width=device-width, initial-scale=1.0');

$this->headTitle()->setSeparator(' · ');
$this->headTitle()->enableTranslation();
$this->headTitle('Tillikum');

$this->headLink()->appendStylesheet("{$this->baseUrl()}/public/styles/tillikum.css?@@tillikumCssHash@@", 'all');
$this->headScript()->appendScript('var BASE = \'' . $this->baseUrl() . '\';');
$this->headScript()->appendScript('var LOCALE = \'' . Locale::getDefault() . '\';');
$this->headScript()->appendFile("{$this->baseUrl()}/public/scripts/tillikum.js?@@tillikumJsHash@@");

echo $this->doctype();
?>
<html ng-app="tillikum" lang="en" dir="ltr">
  <head>
    <?php
    echo $this->headMeta();
    echo $this->headTitle();
    echo $this->headLink();
    echo $this->headScript();
    ?>
  </head>
  <body>
    <header class="clearfix">
      <nav>
        <a id="tillikum-logo"
           href="<?php echo $this->url(array(), null, true) ?>"
           title="<?php echo $this->translate('Tillikum Home') ?>"
        ><img src="<?php echo "{$this->url(array(), null, true)}public/images/tillikum-logo.png" ?>"
              alt="<?php echo $this->translate('Tillikum fish logo') ?>" /></a>
<?php if ($this->layout()->siteLogoNavigation): ?>
        <a id="site-logo"
           href="<?php echo $this->layout()->siteLogoNavigation->href ?>"
           title="<?php echo $this->layout()->siteLogoNavigation->title ?>"
        ><img src="<?php echo "{$this->url(array(), null, true)}public/images/site-logo.png" ?>"
              alt="<?php echo $this->layout()->siteLogoNavigation->alt ?>" /></a>
<?php endif ?>
      </nav>
    </header>
    <div id="content-wrapper">
      <div class="yui3-g">
        <div id="sidenav-wrapper" class="yui3-u-1-8">
          <nav>
            <?php echo $this->navigation()->menu($this->layout()->sideNavigation) ?>
          </nav>
        </div>
        <div id="main-wrapper" class="yui3-u-7-8">
          <?php echo $this->layout()->content ?>
        </div>
      </div>
    </div>
    <footer>
      <div class="yui3-g">
        <div class="yui3-u-1-2" style="text-align: left;">
          <nav>
            <ul>
              <li><?php echo $this->translate('Learn more about the <a href="http://tillikum.org" target="_blank">Tillikum project</a>.') ?>
            </ul>
          </nav>
        </div>
        <div class="yui3-u-1-2" style="text-align: right;">
<?php if (count($this->layout()->translations) > 0): ?>
          <nav>
            <ul>
  <?php foreach ($this->layout()->translations as $translation): ?>
    <?php if ($translation['selected']): ?>
              <li><mark><?php echo $this->escape($translation['text']) ?></mark></li>
    <?php else: ?>
              <li><?php echo $this->escape($translation['text']) ?></li>
    <?php endif ?>
  <?php endforeach ?>
            </ul>
          </nav>
<?php endif ?>
        </div>
      </div>
    </footer>
  </body>
</html>
