<?php

$this->headMeta()->setCharset($this->getEncoding());
$this->headMeta()->setHttpEquiv('X-UA-Compatible', 'IE=edge env=best-standards-support');
$this->headMeta()->setName('viewport', 'width=device-width, initial-scale=1.0');

$this->headTitle()->setSeparator(' · ');
$this->headTitle()->enableTranslation();
$this->headTitle('Tillikum');

$this->headLink()
    ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/angular-ui/0.4.0/angular-ui.min.css', 'all')
    ->appendStylesheet($this->baseUrl('public/build/tillikum.css?d82f01cf219b37af37519e9ee77bc7df'), 'all');

$this->headScript()
    ->appendScript(sprintf('var Tillikum = %s;', json_encode(array('BASE' => $this->baseUrl(), 'LOCALE' => Locale::getDefault()))))
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/json3/3.2.4/json3.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/angular.js/1.0.6/angular.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/angular-ui/0.4.0/angular-ui.min.js')
    ->appendFile('//cdnjs.cloudflare.com/ajax/libs/angular-ui/0.4.0/angular-ui-ieshiv.min.js')
    ->appendFile($this->baseUrl('public/build/tillikum.js?18f1c2ceb369b4564ea5c59ac85923bd'));
?>
<?php echo $this->doctype() ?>

<html ng-app="tillikum" lang="en" dir="ltr">
  <head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
  </head>
  <body>
    <header class="clearfix">
      <nav>
        <a id="tillikum-logo"
           href="<?php echo $this->url(array(), null, true) ?>"
           title="<?php echo $this->translate('Tillikum Home') ?>"
        ><img src="<?php echo "{$this->url(array(), null, true)}public/images/tillikum-logo.png" ?>"
              alt="<?php echo $this->translate('Tillikum fish logo') ?>" /></a>
<?php if ($this->layout()->siteLogoNavigation): ?>
        <a id="site-logo"
           href="<?php echo $this->layout()->siteLogoNavigation->href ?>"
           title="<?php echo $this->layout()->siteLogoNavigation->title ?>"
        ><img src="<?php echo "{$this->url(array(), null, true)}public/images/site-logo.png" ?>"
              alt="<?php echo $this->layout()->siteLogoNavigation->alt ?>" /></a>
<?php endif ?>
      </nav>
    </header>
    <div id="content-wrapper">
      <div class="yui3-g">
        <div id="sidenav-wrapper" class="yui3-u-1-8">
          <nav>
            <?php echo $this->navigation()->menu($this->layout()->sideNavigation) ?>
          </nav>
        </div>
        <div id="main-wrapper" class="yui3-u-7-8">
          <?php echo $this->layout()->content ?>
        </div>
      </div>
    </div>
    <footer>
      <div class="yui3-g">
        <div class="yui3-u-1-2" style="text-align: left;">
          <nav>
            <ul>
              <li><?php echo $this->translate('Learn more about the <a href="http://tillikum.org" target="_blank">Tillikum project</a>.') ?>
            </ul>
          </nav>
        </div>
        <div class="yui3-u-1-2" style="text-align: right;">
<?php if (count($this->layout()->translations) > 0): ?>
          <nav>
            <ul>
  <?php foreach ($this->layout()->translations as $translation): ?>
    <?php if ($translation['selected']): ?>
              <li><mark><?php echo $this->escape($translation['text']) ?></mark></li>
    <?php else: ?>
              <li><?php echo $this->escape($translation['text']) ?></li>
    <?php endif ?>
  <?php endforeach ?>
            </ul>
          </nav>
<?php endif ?>
        </div>
      </div>
    </footer>
  </body>
</html>
